version: '3'

services:

  rabbit:
    restart: always
    container_name: rabbit_mq_psction
    ports:
      - 5672:5672
    image: "rabbitmq:3"

  postgres:
    image: postgres:13
    container_name: postgres_name
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pass
      PGDATA: /tmp
      PGPORT: 5432

  web:
    build:
      context: .
    image: psction
    environment:
      - PSC_DEBUG=1
      - PSC_SECRET_KEY=^l@qy)%%6i940u3n4w*f77t-e^71tf#=_9ygq48fig)(4py!v*
      - CLINIC_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA
      - PATIENT_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA
      - PHYSICIAN_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA
      - METRIC_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA
    command: >
      sh -c "coverage run manage.py test prescription && python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbit

  celery-worker:
    build: .
    volumes:
      - .:/src
    command: celery -A psction worker -l INFO
    depends_on:
      - web
      - rabbit
      - postgres

  celery-beat:
    build: .
    user: root
    volumes:
      - .:/src
    command: celery -A psction beat -l INFO
    depends_on:
      - web
      - rabbit
      - postgres
