version: "3"

services:
  rabbit:
    restart: always
    container_name: rabbit_mq_psction
    ports:
      - 5672:5672
    image: "rabbitmq:3"

  postgres:
    restart: always
    image: postgres:13
    container_name: postgres_name
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pass
      PGDATA: /tmp
      PGPORT: 5432

  web:
    restart: always
    build:
      context: .
    image: psction
    volumes:
      - .:/src
    env_file:
      - .env
    command: >
      sh -c "coverage run manage.py test prescription && python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbit

  celery-worker:
    build: .
    volumes:
      - .:/src
    command: celery -A psction.celery worker -l INFO
    depends_on:
      - web
      - rabbit
      - postgres

  celery-beat:
    build: .
    user: root
    volumes:
      - .:/src
    command: celery -A psction.celery beat -l INFO
    depends_on:
      - web
      - rabbit
      - postgres
